### ISSUE TITLE
JsonParseException: Unexpected character ('<' (code 60)):

### ISSUE THREAD

**Issue by XuYang5478** [marwincn/pubsenti-finder#2]
您好，我在运行您的代码时，爬取微博的时候每条都出现了这样的异常：![err](https://gitee.com/XuYang5478/PicGo/raw/master/img/err.png)然后在网页中图表和评论列表会一直重复出现，网页变得老长老长，请问您有遇到过这样的异常吗？是怎样解决的呢？

**Comment by marwincn** [comment]
这个异常出现在Jackson解析请求weibo的响应中，如果响应正常应该返回的是json数据，如果响应异常就会返回一个错误页的html，Jackson不能解析html所以抛出了这个异常。
你可以在获取weibo或者评论的请求后面打印响应的string看错误的响应是什么，导致这个异常的原因主要有请求的链接错误或者cookie错误。

**Comment by marwincn** [comment]
> 您好，我在运行您的代码时，爬取微博的时候每条都出现了这样的异常：![err](https://camo.githubusercontent.com/8e04f7b35e8c83cd2da32a1dabc5b291bcaf1432/68747470733a2f2f67697465652e636f6d2f587559616e67353437382f506963476f2f7261772f6d61737465722f696d672f6572722e706e67)然后在网页中图表和评论列表会一直重复出现，网页变得老长老长，请问您有遇到过这样的异常吗？是怎样解决的呢？

我把cookie注释掉可以复现你的问题，所以大概率可能你的cookie没有设置对，或者cookie已经失效。这样只能获取每条微博的第一页评论，到第二页就会抛出异常。

正确的cookie格式如下，将红框中的一大段字符串都复制到`HttpUtil`类的对应位置中。
![截屏](https://i.loli.net/2020/04/13/FnRdUlHZaEubBiG.png)

**Comment by XuYang5478** [comment]
是的，是我没有设置对cookie的原因，现在已经好啦，感谢🙇‍
